version: '3.9'

services:
  db:
    container_name: gardens_db
    image: postgres
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    environment: 
    - "POSTGRES_HOST_AUTH_METHOD=trust"
  
  app:
    build:
      context: .
    container_name: gardens_app
    user: root
    volumes:
      - static_data:/vol/web/static
      - media_data:/vol/web/media
      
    environment:
      - SECRET_KEY=samplesecretkey123
      - ALLOWED_HOSTS=127.0.0.1,localhost
    depends_on:
      - db
  
  proxy:
    build:
      context: ./proxy
    container_name: gardens_proxy
    volumes:
      - static_data:/vol/static
      - media_data:/vol/media
    ports:
      - "8080:8080"
    depends_on:
      - app

volumes:
  static_data:
  media_data: