# Generated by Django 3.0.4 on 2020-12-27 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gardens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GettingStarted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Terrariums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='SubCategory',
            new_name='Diy',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='subcategory',
            new_name='diy',
        ),
        migrations.AddField(
            model_name='post',
            name='gardens',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Gardens'),
        ),
        migrations.AddField(
            model_name='post',
            name='getting_started',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.GettingStarted'),
        ),
        migrations.AddField(
            model_name='post',
            name='terrariums',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Terrariums'),
        ),
    ]
