# Generated by Django 3.0.4 on 2020-12-27 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201227_1937'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gardens',
            new_name='Garden',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='gardens',
            new_name='garden',
        ),
    ]
