# Generated by Django 3.0.4 on 2020-12-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201227_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='diy',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
        migrations.AddField(
            model_name='garden',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
        migrations.AddField(
            model_name='gettingstarted',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
        migrations.AddField(
            model_name='terrariums',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
