# Generated by Django 3.0.4 on 2020-12-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201228_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='garden',
        ),
    ]
