# Generated by Django 3.0.4 on 2020-12-28 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_post_garden'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='garden',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Garden'),
        ),
    ]
