# Generated by Django 3.0.4 on 2020-12-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_post_garden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='garden',
        ),
        migrations.DeleteModel(
            name='Garden',
        ),
    ]
