# Generated by Django 3.0.4 on 2020-12-28 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201228_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gardens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='gardens',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Gardens'),
        ),
    ]
