# Generated by Django 3.0.4 on 2020-12-28 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201228_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gettingstarted',
            name='post',
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=100)),
                ('getting_started', models.ForeignKey(default=1, max_length=100, on_delete=django.db.models.deletion.PROTECT, to='core.GettingStarted')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Categories'),
        ),
    ]
