# Generated by Django 3.0.4 on 2020-12-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201228_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='terrariums',
        ),
        migrations.DeleteModel(
            name='Terrariums',
        ),
    ]
