# Generated by Django 3.0.4 on 2020-12-28 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20201228_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='diy',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Diy'),
        ),
        migrations.AlterField(
            model_name='post',
            name='gardens',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Gardens'),
        ),
        migrations.AlterField(
            model_name='post',
            name='getting_started',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.GettingStarted'),
        ),
        migrations.AlterField(
            model_name='post',
            name='terrariums',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Terrariums'),
        ),
    ]
