# Generated by Django 3.0.4 on 2020-12-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20201228_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diy',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='gardens',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='gettingstarted',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='terrariums',
            name='slug',
        ),
    ]
