# Generated by Django 3.0.4 on 2020-12-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201228_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='diy',
        ),
        migrations.RemoveField(
            model_name='post',
            name='gardens',
        ),
        migrations.RemoveField(
            model_name='post',
            name='terrariums',
        ),
    ]
