# Generated by Django 3.0.4 on 2020-12-28 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20201228_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='diy',
        ),
        migrations.RemoveField(
            model_name='post',
            name='gardens',
        ),
        migrations.RemoveField(
            model_name='post',
            name='getting_started',
        ),
        migrations.RemoveField(
            model_name='post',
            name='terrariums',
        ),
        migrations.AlterField(
            model_name='diy',
            name='name',
            field=models.CharField(blank=True, default='none', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gardens',
            name='name',
            field=models.CharField(blank=True, default='none', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gettingstarted',
            name='name',
            field=models.CharField(blank=True, default='none', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diy', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Diy')),
                ('gardens', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Gardens')),
                ('getting_started', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.GettingStarted')),
                ('terrariums', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Terrariums')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Category'),
        ),
    ]
