# Generated by Django 3.0.4 on 2020-12-28 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20201228_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.AddField(
            model_name='post',
            name='diy',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Diy'),
        ),
        migrations.AddField(
            model_name='post',
            name='gardens',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Gardens'),
        ),
        migrations.AddField(
            model_name='post',
            name='getting_started',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.GettingStarted'),
        ),
        migrations.AddField(
            model_name='post',
            name='terrariums',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Terrariums'),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
