# Generated by Django 3.0.4 on 2020-12-30 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20201228_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='diy',
        ),
        migrations.RemoveField(
            model_name='post',
            name='gardens',
        ),
        migrations.RemoveField(
            model_name='post',
            name='terrariums',
        ),
        migrations.DeleteModel(
            name='Diy',
        ),
        migrations.DeleteModel(
            name='Gardens',
        ),
        migrations.DeleteModel(
            name='Terrariums',
        ),
    ]
