# Generated by Django 3.0.4 on 2020-12-30 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Category2'),
        ),
    ]
