# Generated by Django 3.0.4 on 2020-12-30 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_post_category2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category2',
        ),
    ]
