# Generated by Django 3.0.4 on 2020-12-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_delete_category2'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
