# Generated by Django 3.0.4 on 2020-12-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_category_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_type',
        ),
    ]
