# Generated by Django 3.0.4 on 2020-12-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_category_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='kind',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
