# Generated by Django 3.0.4 on 2021-01-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20210103_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='kind',
            field=models.CharField(choices=[('GS', 'Getting Started'), ('DIY', 'DIY'), ('GR', 'Gardens'), ('TR', 'Terrariums')], default=' ', max_length=3),
        ),
    ]
