# Generated by Django 3.0.4 on 2021-03-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='content',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
    ]
