# Generated by Django 3.0.4 on 2021-03-11 14:45

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20210311_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
